
# name: Publish to pub.dev

# on:
#   push:
#     tags:
#     - 'v[0-9]+.[0-9]+.[0-9]+*' 


# jobs:
#   publish:
#     permissions:
#       id-token: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: dart-lang/setup-dart@v1
#       - name: Setup Flutter
#         run: |
#           git clone https://github.com/flutter/flutter.git --depth 1 -b stable
#           echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
#       - name: Install dependencies
#         run: flutter pub get

#       - name: Publish
#         run: dart pub publish --force
